version: 2
jobs:
  build:
    docker:
      # - image: circleci/python:3.5
      - image: circleci/python:3.6
      # - image: circleci/python:3.7
      # - image: circleci/python:3.8-rc
    steps:
      - checkout
      - run: sudo chown -R circleci.circleci /usr/local/bin
      - run: sudo chown -R circleci.circleci /usr/local/bin/python3.6/site-packages
      - restore_cache:
          key: sdnify-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - save_cache:
          key: sdnify-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/bin/python3.6/site-packages"
      - run:
          command: |
            py.test tests/
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
